ruby-backend/config/routes.rb
Rails.application.routes.draw do

  get 'home/home'

  root                  'home#home'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users,               path: 'utilisateurs'
  resources :account_activations, path: 'activation',       only: [:edit]
  resources :password_resets,                               only: [:new, :create, :edit, :update]

  resources :subjects,            path: 's', param: :subject_id do
    member do
      resources :positions,       as: 'subjects_positions', only: [:index]
      resources :statements,      as: 'subjects_statements'
    end
  end
  resources :public_figures,      path:'p', param: :public_figure_id do
    member do
      resources :statements,      as: 'public_figures_statements'
    end
  end
  resources :positions,                                     only: [:create, :update, :destroy]
  resources :statements,                                    only: [:new, :create, :update, :destroy]
  resources :arguments,                                     only: [:create, :update, :destroy]

  get 'autocomplete/autocomplete_subject_title'
  get 'autocomplete/autocomplete_position_title'
  get 'autocomplete/autocomplete_public_figure_name'

  get 'a-propos',             to: 'static_pages#a_propos',      as: 'a_propos'
  get 'contact',              to: 'static_pages#contact',       as: 'contact'
  get 'mode_demploi',         to: 'static_pages#mode_demploi',  as: 'mode_demploi'
  get 'error',                to: 'static_pages#error',  as: 'error'

  get 'home'   => 'home#home'

end

ruby-backend/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token

  ## DEFAULT VALUES
  after_initialize :default_values

  ## NAME VALIDATION
  validates :name,
      presence: true,
      length: {maximum: 50}

  validates :reputation,
      presence: true

  ## EMAIL VALIDATION
  VALID_EMAIL_REGEX =/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,
      presence: true,
      length: {maximum: 255},
      format: {with:VALID_EMAIL_REGEX},
      uniqueness: {case_sensitive: false}

  ## PASSWORD MANAGEMENT
  has_secure_password
  ## PASSWORD VALIDATION
  validates :password, length: {minimum: 8}, allow_blank: true

  ## EMAIL ALWAYS IN DOWNCASE
  before_save { self.email.downcase! }

  ## ACTIVATION DIGEST CREATION
  before_create :create_activation_digest


  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # token matches the digest ?
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # forget remembered session
  def forget
    update_attribute(:remember_digest, nil)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private
    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

    def default_values
      self.reputation ||= 0
    end

  class << self

    # Returns a digest
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end

  end

end

ruby-backend/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :self_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      log_in(@user)
      flash[:success] = "Bienvenue #{@user.name} ! Veuillez consultez vos e-mails pour valider votre compte."
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Modifications enregistrées !"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Before Filters

    # only if correct user
    def self_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)
    end

end

ruby-backend/app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = {size:80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

ruby-backend/app/views/users/edit.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <%= f.label :name, "Nom" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email, "Courriel"%>
        <%= f.email_field :email, class: 'form-control'  %>

        <%= f.label :password, "Mot de passe" %>
        <%= f.password_field :password, class: 'form-control'  %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control'  %>

        <%= f.submit "Enregistrer", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

ruby-backend/app/views/users/new.html.erb
<% provide(:title, "S'inscrire") %>
<h1>S'inscrire</h1>
<p>Vous êtes sur la voie du débat.</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <%= f.label :name, "Nom" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email, "Courriel"%>
        <%= f.email_field :email, class: 'form-control'  %>

        <%= f.label :password, "Mot de passe" %>
        <%= f.password_field :password, class: 'form-control'  %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control'  %>

        <%= f.submit "Créer mon compte", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

ruby-backend/app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-1"></div>
  <aside class="col-md-4">
    <section class="user_info">
        <h1>
          <%= gravatar_for @user, {size:160} %>
          <%= @user.name %>
        </h1>
        <h2>
          <p>Points de réputation : <%= @user.reputation %> </p>
        </h2>

      <%= link_to "Modifier", edit_user_path(@user), class: "btn btn-primary" %>
      </p>
    </section>
  </aside>
</div>