ruby-backend/config/routes.rb
Rails.application.routes.draw do

  get 'home/home'

  root                  'home#home'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users,               path: 'utilisateurs'
  resources :account_activations, path: 'activation',       only: [:edit]
  resources :password_resets,                               only: [:new, :create, :edit, :update]

  resources :subjects,            path: 's', param: :subject_id do
    member do
      resources :positions,       as: 'subjects_positions', only: [:index]
      resources :statements,      as: 'subjects_statements'
    end
  end
  resources :public_figures,      path:'p', param: :public_figure_id do
    member do
      resources :statements,      as: 'public_figures_statements'
    end
  end
  resources :positions,                                     only: [:create, :update, :destroy]
  resources :statements,                                    only: [:new, :create, :update, :destroy]
  resources :arguments,                                     only: [:create, :update, :destroy]

  get 'autocomplete/autocomplete_subject_title'
  get 'autocomplete/autocomplete_position_title'
  get 'autocomplete/autocomplete_public_figure_name'

  get 'a-propos',             to: 'static_pages#a_propos',      as: 'a_propos'
  get 'contact',              to: 'static_pages#contact',       as: 'contact'
  get 'mode_demploi',         to: 'static_pages#mode_demploi',  as: 'mode_demploi'
  get 'error',                to: 'static_pages#error',  as: 'error'

  get 'home'   => 'home#home'

end

ruby-backend/app/models/public_figure.rb
class PublicFigure < ActiveRecord::Base
  has_many :statements, dependent: :destroy
  has_many :positions, through: :statements, source: :position
  has_many :subjects, through: :positions, source: :subject
  mount_uploader :picture, PictureUploader

  ## VALIDATION
  validates_presence_of :name, :presentation
  validates :name, length: {maximum: 100},  uniqueness: {case_sensitive: false}
  validates :slug, length: {minimum: 3},    uniqueness: {case_sensitive: false}
  validate :picture_size

  # Friendly ID
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders, :history]

  def should_generate_new_friendly_id?
    name_changed? || super
  end

  def associated_subjects
    statements                                # Statements of this personality
        .reject(&:new_record?)                # Ignore new records
        .map(&:position)                      # get position of each statement
        .map(&:subject)                       # get subject of each position
        .uniq                                 # dedupe
  end

  def major?
    created_at > 1.week.ago || statements.size > 2
  end

  def minor?
    !major?
  end

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "L'image ne doit pas dépasser 5 Mo")
    end
  end

end

ruby-backend/app/controllers/public_figures_controller.rb
class PublicFiguresController < ApplicationController
  respond_to :html, :json
  before_action :find_public_figure, only: :show
  before_action :check_reputation_to_destroy, only: :destroy
  before_action :check_reputation_to_add, only: [:new, :create]


  def index
    @public_figures = PublicFigure.paginate(page: params[:page])
    @latest_statements = Statement.latest
  end

  def show
    @public_figure = PublicFigure.find(params[:public_figure_id])
    @new_statement = @public_figure.statements.build
    @latest_statements = Statement.latest
  end

  def new
    @public_figure = PublicFigure.new
    respond_modal_with @public_figure
  end

  def create
    @public_figure = PublicFigure.new(public_figure_params)
    if @public_figure.save
      flash[:success] = "Personnalité \"#{@public_figure.name}\" référencée ! "
      redirect_to @public_figure
    else
      render "new"
    end
  end

  def destroy
    public_figure = PublicFigure.find(params[:public_figure_id])
    name = public_figure.name
    public_figure.destroy  #TODO Mark deleted instead of really deleting record
    flash[:success] = "\"#{name}\" supprimé"
    redirect_to public_figures_url
  end

  private

  def public_figure_params
    params.require(:public_figure).permit(:name, :presentation, :picture)
  end

  def check_reputation_to_destroy
    if !current_user
      store_location
      flash[:danger] = "Vous devez être identifié pour supprimer une personnalité"
      redirect_to login_url
    else
      @public_figure = PublicFigure.find(params[:public_figure_id])
      if @public_figure.major? && !allowed_to?(:delete_major_personality) ||
          @public_figure.minor? && !allowed_to?(:delete_minor_personality)
        flash[:danger] = "Vous n'avez pas assez de réputation pour supprimer une personnalité"
        redirect_to(PublicFigure.find(params[:public_figure_id]))
      end
    end
  end

  def check_reputation_to_add
    if !current_user
      store_location
      flash[:danger] = "Vous devez être identifié pour ajouter une personnalité"
      redirect_to login_url
    elsif !allowed_to? :add_personality
      flash[:danger] = "Vous n'avez pas assez de réputation pour ajouter une personnalité"
      redirect_to public_figures_url
    end
  end

  def find_public_figure
    @public_figure = PublicFigure.find params[:public_figure_id]
    if request.path != public_figure_path(@public_figure)       # If old URL
      redirect_to @public_figure, status: :moved_permanently    # Redirect to new URL
    end
  end

end

ruby-backend/app/helpers/public_figures_helper.rb
module PublicFiguresHelper
end

ruby-backend/app/views/public_figures/_public_figure.html.erb
<table class="table">
  <tbody>

   
     <ul id="subject">
     <li>

     <tr>
      <td>
      <% if public_figure.picture? %>
	  <div style="height:100px; width: 100px; -webkit-border-radius: 50%; border-radius: 50%; background: url('<%= public_figure.picture.url %>') 50% 50% no-repeat; background-size:cover; background-position: center center; float:left; margin-right:15px;"></div>
		<% end %>
      </td>
      <td style="width:33%;">

      	<h2 class="figure-title" style="color:#333333 !important;"><%= link_to public_figure.name, public_figure %>
      	</h2>

        <% if public_figure.subjects.count == 0 %> <h6 style="color:#f21e40 !important;"> Aucun sujet actif</h6>
        <% else %>
      	<h6 style="color:#f21e40 !important;"><%= public_figure.subjects.count%>
          <% if public_figure.subjects.count > 1%>  sujets actifs</h6>
          <% else %> sujet actif</h6>
          <% end %>
        <% end %>

      </td>


      <td style="width:67%; text-align:center;vertical-align:top;padding-top:20px;border:none;">

       <p class="figure-presentation-text" style="font-size:13px !important;"><%= public_figure.presentation %></p>


      </td>

      
 
         </tr>
        </li>
        
    </ul>
   
  </tbody>
</table>

<script type="text/javascript">
    $(document).ready(function() {
     
        $(".figure-presentation-text").shorten();
     
    });
</script>

ruby-backend/app/views/public_figures/_statement.html.erb
<li>
  Au sujet de
  <%= link_to statement.position.subject.title, statement.position.subject %>
  <br><%= pluralize(subject.positions.count, 'positions') %>, <%= pluralize(subject.statements.count, 'prise de position') %>
  <br><br>
  <%= link_to statement.position.title, statement.position %>
  <br>TAGS ASSOCIES    
</li>

ruby-backend/app/views/public_figures/index.html.erb
<% provide(:title, "Personnalités") %>
<div class="container-fluid" style="width:100vw; position:relative; margin-left:-50vw;left:50%;">
    <div class="col-md-7 col-md-offset-1">
        <h1>Les Personnalités 
        </h1>
        <%= link_to "Référencer une personnalité", new_public_figure_path, class: "btn btn-primary", data: { modal: true } if allowed_to?(:add_personality) %>
        <p><%= link_to "Test : modal d'ajout", new_statement_path, data: { modal: true } %> </p>
        <div class="public-figures-index">
            <%= render @public_figures %>
        </div>
    </div>
    <div class="col-md-3">
        <%= render 'layouts/last_statements' %>
        <%= will_paginate %>
    </div>
    <div class="col-md-1"></div>
</div>

ruby-backend/app/views/public_figures/new.html.erb
<% provide(:title, "Nouvelle personnalité") %>
<h1>Nouvelle personnalité</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@public_figure, html: {multipart:true}) do |f| %>
        <%= render "shared/error_messages", object: f.object %>

        <%= f.label :name, "Nom" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :presentation, "Présentation"%>
        <%= f.text_area :presentation, class: 'form-control'  %>

        <span class="picture" ><%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %></span>

        <%= f.submit "Créer cette personnalité", class: "btn btn-primary" %>
    <% end %>
    <script type="text/javascript">
        $("#public_figure_picture").bind('change', function() {
            var size_in_MB = this.files[0].size/1024/1024;
            if (size_in_MB > 5) {
                alert("L'image ne doit pas dépasser 5 Mo. Veuillez choisir un fichier plus léger. ");
            }
        })
    </script>
  </div>
</div>

ruby-backend/app/views/public_figures/show.html.erb
<% provide(:title, @public_figure.name ) %>

<!-- bloc description de la personnalité -->
<div class="row" style="margin-top:20px;">
<div class="col-md-1"></div>
<div class="col-md-1">
  <div class="publicfigurehead">
    <% if @public_figure.picture? %>
    <div style="background: url('<%= @public_figure.picture.url%>') 50% 50% no-repeat; background-size:cover;background-position: center center;" class="publicfigurethumb"></div>
    <% end %>
  </div>
</div>


<div class="col-md-3">



<div class="publicfiguredescription">
<h1 id="PublicFigureTitle">
<% if allowed_to? :edit_minor_personality %>
  <%= best_in_place @public_figure, :name %>
  <% else %>
  <%= @public_figure.name %>
  <% end %>
</h1>

<p class="figure-presentation-text"><%= @public_figure.presentation %></p>
</div>

</div>

<div>
<% if @public_figure.major? && allowed_to?(:delete_major_personality) ||
    @public_figure.minor? && allowed_to?(:delete_minor_personality) %>
    <%=       link_to "Supprimer", @public_figure,
                      method: :delete,
                      data: { confirm: "Supprimer \"#{@public_figure.name}\" ?" },
                      class: "btn btn-primary btn-danger" %>
<% end %>

</div>
</div>
<!-- END bloc description de la personnalité -->

<!-- END content -->
<div class="row">
<div class="col-md-1"></div>

<div class="col-md-7">
  <table class="table">
    <tbody>
      <tr>
        <td><h1>Sujets Actifs</h1></td>
        <td><h1><%= t('statements_count', count: @public_figure.statements.count) %></h1></td>
      </tr>
      <% if @public_figure.statements.any? %>
      <ul class="subjects">
      <% @public_figure.associated_subjects.each do |subject| %>
       <li> 
        <tr>
          <td>
              <%= subject.title %>
          </td>
          <td>
              <% subject.get_positions_for_public_figure(@public_figure).each do |position| %>
                <%= position.title %>
              <% end %>
          </td>
        </tr>
        </li>
        <% end %>
      </ul>
      <% end %>

    </tbody>
  </table>
</div>



<div class="col-md-3">
  <div id="last-statements">
    <h2>Les dernières prises de position</h2>
    <ul id="last-statements">
      <% @latest_statements.each do |statement| %>
          <li id="statement-<%= statement.id %>" style="margin-bottom: 20px;">
            <% if statement.public_figure.picture? %>
     <div style="height:50px; width: 50px; -webkit-border-radius: 50%; border-radius: 50%; background: url('<%= statement.public_figure.picture.url %>') 50% 50% no-repeat; background-size:cover; background-position: center center; float:left; margin-right:15px;"></div>
        <% end %>
            <div class="public-figure-text"><strong>
            <%= link_to statement.public_figure.name, statement.public_figure %></strong>&nbsp; s'est déclaré pour
            "<strong><%= statement.position.title %></strong>"
            dans le débat sur
            <strong><%= link_to statement.position.subject.title, statement.position.subject %></strong></div>
          </li>
      <% end %>
    </ul>
</div>
</div>

<div class="col-md-1"></div>
</div>
<!-- END bloc content -->

<div class="row">
  <div class="col-md-10 col-md-offset-1">
            <% #= render partial: "statement", collection:@public_figure.statements.select { |s| s.id }, as: :statement %>

        <% if logged_in? && allowed_to?(:add_statement) %>
            <li id="new-statement">
              <%= form_for(@new_statement) do |f| %>
                  <%= render 'shared/error_messages', object: f.object %>
                  <%= f.hidden_field :public_figure_id, :value => @public_figure.id %>

                  <%= f.fields_for @new_statement.evidences.build do |e| %>
 
                     <%= e.label :url, "Lien internet ..." %>
                      <%= e.text_field :url, placeholder: "http://" %>
                      <%= e.label :file, "... ou pièce jointe" %>
                      <%= e.file_field :file, accept: 'image/jpeg,image/gif,image/png,application/pdf,audio/mpeg3,audio/x-mpeg3,video/avi,video/quicktime,audio/wav', class: 'btn btn-primary' %>
                      <%= e.label :title, "Intitulé de la preuve" %>
                      <%= e.text_field :title, placeholder: "Explicitez la référence" %>
                      <%= e.label :fact_date, "Date des faits" %>
                      <%= e.text_field :fact_date, placeholder: "jj/mm/yyyy", class: "Datepicker" %>

                  <% end %>
                  <%= label_tag "Sujet" %>
                  <%= autocomplete_field_tag 'Subject', '',
                                             autocomplete_autocomplete_subject_title_path,
                                             id_element: '#statement_subject_id',
                                             class: "Autocomplete"
                  %>
                  <%= f.hidden_field :subject_id, value: "",
                                     data: {
                                             dynamic_selectable_url: subjects_positions_path(':subject_id', format: :json),
                                             dynamic_selectable_target: '#statement_position_id'
                                     }
                                      %>

                  <%= f.label :position_id, "Position prise" %>
                  <%= f.select :position_id, {} %>
          
                  <%= f.submit "Ajouter", class: "btn btn-primary" %>

              <% end %>

            </li>
        <% end %>

  </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
     
        $(".figure-presentation-text").shorten();
     
    });
</script>