ruby-backend/config/routes.rb
Rails.application.routes.draw do

  get 'home/home'

  root                  'home#home'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users,               path: 'utilisateurs'
  resources :account_activations, path: 'activation',       only: [:edit]
  resources :password_resets,                               only: [:new, :create, :edit, :update]

  resources :subjects,            path: 's', param: :subject_id do
    member do
      resources :positions,       as: 'subjects_positions', only: [:index]
      resources :statements,      as: 'subjects_statements'
    end
  end
  resources :public_figures,      path:'p', param: :public_figure_id do
    member do
      resources :statements,      as: 'public_figures_statements'
    end
  end
  resources :positions,                                     only: [:create, :update, :destroy]
  resources :statements,                                    only: [:new, :create, :update, :destroy]
  resources :arguments,                                     only: [:create, :update, :destroy]

  get 'autocomplete/autocomplete_subject_title'
  get 'autocomplete/autocomplete_position_title'
  get 'autocomplete/autocomplete_public_figure_name'

  get 'a-propos',             to: 'static_pages#a_propos',      as: 'a_propos'
  get 'contact',              to: 'static_pages#contact',       as: 'contact'
  get 'mode_demploi',         to: 'static_pages#mode_demploi',  as: 'mode_demploi'
  get 'error',                to: 'static_pages#error',  as: 'error'

  get 'home'   => 'home#home'

end

ruby-backend/app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action     :valid_user,        only:[:edit, :update]
  before_action     :check_expiration,  only:[:edit, :update]

  def new
  end

  def create
    @user = User.find_by_email(params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Un e-mail vous a été envoyé. Veuillez en suivre les instructions pour créer un nouveau mot de passe. "
      redirect_to root_url
    else
      flash.now[:danger] = "Aucun utilisateur avec cette adresse e-mail. Veuillez vérifier votre saisie. "
      render "new"
    end
  end

  def edit
    if (!@user.activated?)
      @user.activate
    end
  end

  def update
    if params[:user][:password].blank?
      flash.now[:danger] = "Vous devez choisir un mot de passe"
      render "edit"
    elsif @user.update_attributes(params.require(:user).permit(:password, :password_confirmation))
      log_in @user
      flash[:success] = "Nouveau mot de passe enregistré !"
      redirect_to @user
    else # Could not save new password (check validations)
      render "edit"
    end
  end

  private

    def valid_user
      @user = User.find_by_email(params[:email])
      if (!@user || !@user.authenticated?(:reset, params[:id]))
        flash[:danger] = "Lien incorrect."
        redirect_to root_url
      end
    end

    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Lien expiré. Veuillez renouveller votre demande. "
        redirect_to new_password_reset_url
      end
    end
end

ruby-backend/app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

ruby-backend/app/views/password_resets/edit.html.erb
<% provide(:title, "Nouveau mot de passe")%>
<h1>Nouveau mot de passe</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= hidden_field_tag :email, @user.email %>

        <%= f.label "Nouveau mot de passe" %>
        <%= f.password_field :password, class: "form-control" %>

        <%= f.label "Confirmez" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>

        <%= f.submit "Enregistrer", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

ruby-backend/app/views/password_resets/new.html.erb
<% provide(:title, "Mot de passe oublié") %>
<h1>Mot de passe oublié</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
        <%= f.label "Adresse e-mail" %>
        <%= f.email_field :email, class: "form-control" %>
        <%= f.submit "Nouveau mot de passe", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>