ruby-backend/config/routes.rb
Rails.application.routes.draw do

  get 'home/home'

  root                  'home#home'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users,               path: 'utilisateurs'
  resources :account_activations, path: 'activation',       only: [:edit]
  resources :password_resets,                               only: [:new, :create, :edit, :update]

  resources :subjects,            path: 's', param: :subject_id do
    member do
      resources :positions,       as: 'subjects_positions', only: [:index]
      resources :statements,      as: 'subjects_statements'
    end
  end
  resources :public_figures,      path:'p', param: :public_figure_id do
    member do
      resources :statements,      as: 'public_figures_statements'
    end
  end
  resources :positions,                                     only: [:create, :update, :destroy]
  resources :statements,                                    only: [:new, :create, :update, :destroy]
  resources :arguments,                                     only: [:create, :update, :destroy]

  get 'autocomplete/autocomplete_subject_title'
  get 'autocomplete/autocomplete_position_title'
  get 'autocomplete/autocomplete_public_figure_name'

  get 'a-propos',             to: 'static_pages#a_propos',      as: 'a_propos'
  get 'contact',              to: 'static_pages#contact',       as: 'contact'
  get 'mode_demploi',         to: 'static_pages#mode_demploi',  as: 'mode_demploi'
  get 'error',                to: 'static_pages#error',  as: 'error'

  get 'home'   => 'home#home'

end

ruby-backend/app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="col-md-1"></div>
<div class="col-md-3">
<small>
    <a href="#">Crédits</a>
    |
    <a href="#">Mentions Légales</a>
  </small></div>
  <div class="col-md-7">
  <nav>
    <ul>
      <li><%= link_to "À propos",  a_propos_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://twitter.com/debatsco" target="_blank">Twitter</a></li>
    </ul>
  </nav>
  </div>
  <div class="col-md-1"></div>
</footer>

ruby-backend/app/views/layouts/_header.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<header class="navbar navbar-fixed-top navbar-custom">
  <div class="container-fluid">
  <div class="col-md-1"></div>
   <div class="col-md-2"> <%= link_to image_tag("header.png"), root_path, id:"logo" %></div>
   <div class="col-md-8">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("Subjects"), subjects_path %></li>
        <li><%= link_to t("Public_figures"), public_figures_path %></li>
		<li><%= link_to t("Mode d'emploi"), mode_demploi_path %></li>
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.name %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profil", current_user %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Déconnexion", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
            <li><%= link_to "Connexion", login_path %></li>
            <li><%= link_to "Inscription", new_user_path %></li>
        <% end %>
      </ul>
    </nav>
    </div>
    <div class="col-md-1"></div>
  </div>
</header>

ruby-backend/app/views/layouts/_last_statements.html.erb
<div id="last-statements">
    <h2>Les dernières prises de positions</h2>
    <ul id="last-statements">
      <% # render @latest_statements %>
       <% if @latest_statements %>
      <% @latest_statements.each do |statement| %>
          <li id="statement-<%= statement.id %>" style="margin-bottom: 20px;">
            <% if statement.public_figure.picture? %>
  	 <div style="height:50px; width: 50px; -webkit-border-radius: 50%; border-radius: 50%; background: url('<%= statement.public_figure.picture.url %>') 50% 50% no-repeat; background-size:cover; background-position: center center; float:left; margin-right:15px;"></div>
        <% end %>
            <div class="public-figure-text"><strong>
            <%= link_to statement.public_figure.name, statement.public_figure %></strong>&nbsp; s'est déclaré pour
            "<strong><%= statement.position.title %></strong>"
            dans le débat sur
            <strong><%= link_to statement.position.subject.title, statement.position.subject %></strong></div>
          </li>
      <% end %>
      <% end %>
    </ul>
</div>

ruby-backend/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

ruby-backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body class="fuelux">
<%= render 'layouts/header' %>
<div class="container-fluid">
  <%= flash_messages %>
  <div class="main-content">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
<div id="modal-holder"></div>
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-N4M2L9"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-N4M2L9');</script>
<!-- End Google Tag Manager -->
</body>
</html>

ruby-backend/app/views/layouts/modal.html.erb
<div id="myModal" class="modal fade" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
  <div class="modal-dialog ui-front">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" id="mainModalLabel">
          <%= yield :title if content_for? :title %>&nbsp;
        </h4>
      </div>
      <%= yield %>
    </div>
  </div>
</div>